version: '3.8'

services:
  wave-capital-demo:
    build: .
    ports:
      - "3001:3000"
    restart: always
    networks:
      - westzane-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  westzane-network:
    external: true
